export FLASK_ENV=development
export FLASK_DEBUG=1
export FLASK_APP=src
export SQLALCHEMY_DATABASE_URI=sqlite:///bookmarks.db
export SQLALCHEMY_TRACK_MODIFICATIONS=False
export JWT_SECRET_KEY='2741C988CBE196CE7A2EE3326B61E'